image: gitlab/dind

before_script:
  - docker-compose --version
  - docker --version
build:
  script:
    - ls
    - cd 2-premiere-application/
    - docker-compose up -d

test:
  script:
    - curl localhost:80 

